### ISSUE TITLE
Code Formatter

### ISSUE THREAD

**Issue by umutucak** [Luxembourg-Open-Source-Club/BICS-BOT#2]
Use [Black](https://github.com/psf/black)

Developers should be encouraged to use Visual Studio Code as their IDE in the first few months. Using the same IDE with easy to configure extensions will make starting off easier.

**Comment by PedroS235** [comment]
Create a pyproject.toml with a configuration for black, such that everyone uses the same settings within this repo:

Example:
```toml
# pyproject.toml
[tool.black]
line-length = 88
target-version = ['py36', 'py37', 'py38']
exclude = '''
    /path/to/exclude/
    /path/to/another/exclude/
'''
```
